export const tools = [
    {
      name: "OpenSea",
      description: "The largest NFT marketplace. Buy, sell, & discover the internet of goods.",
      icon: "https://pbs.twimg.com/profile_images/1544105652330631168/ZuvjfGkT_400x400.png",
      twitter: "https://twitter.com/opensea",
      discord: "https://discord.gg/QFZAkbVmjE",
      website: "https://t.co/prq7Jdur5I",
      category: "Marketplace",
      from: "#D8D8D8",
      to: "#3B3B3B",
    },
    {
      name: "Hyperspace",
      description:
        "Solana's best NFT marketplace. Save money sweeping floors by buying across all marketplaces at once.",
      icon: "https://hyperspace.xyz/apple-touch-icon.png",
      twitter: "https://twitter.com/hyperspacexyz",
      discord: "https://discord.gg/3bh6CX5vU6",
      website: "https://hyperspace.xyz/collection/supportivedudes",
      category: "Marketplace,Aggregator,Portfolio Tracker",
      from: "#3C69F7",
      to: "#18317B",
    },
  ];

  export const Holderstools = [
    {
      name: "Zilla VS Kong",
      description:
        "Get an exclusive access to Zilla vs Kong's Sniper Bot !",
      icon: "https://cdn.discordapp.com/attachments/1011202479171571812/1027961050710155274/j0OYQ1WEgr6TkzKJ3oA4Q-yH3uXv68hH5tyU9Vk3xcA.png",
      twitter: "https://twitter.com/Zilla_VS_Kong",
      discord: "https://discord.com/invite/seyEZ8Ekrt",
      website: "https://snapshots-toolkit.com/home",
      category: "Sniper Bot",
      from: "#D32204",
      to: "#746ADE",
    },
    {
      name: "The Incentive",
      description:
        "Earn $EDD by chatting and raiding our tweets",
      icon: "https://pbs.twimg.com/profile_images/1584986632167587848/7PPgaTjy_400x400.jpg",
      twitter: "https://twitter.com/The_Incentive",
      website: "https://www.theincentive.xyz/lp/soleddarity/",
      category: "Raid-2-Earn,Chat-2-Earn",
      from: "#681A82",
      to: "#28122C",
    },
    {
      name: "Own-2-Earn by Soleddarity",
      description:
        "Earn $EDD by holding multiple NFTs and special traits on several NFT collections.",
      icon: "https://st2.depositphotos.com/3491355/7921/v/450/depositphotos_79212646-stock-illustration-diamond-outline-vector-icon-modern.jpg",
      twitter: "https://twitter.com/soleddarity",
      discord: "https://discord.gg/soleddarity",
      website: "https://soleddarity.com",
      category: "Inner Discord,Own-2-Earn",
      from: "#0EFFEA",
      to: "#445D5B",
    },
    {
      name: "{C}IPHER by 313Labs",
      description:
        "Members who apply for Cipherlist will be reviewed and receive a skill-based role within their Discord server.",
      icon: "https://pbs.twimg.com/profile_images/1552350712243580929/KALByWaz_400x400.png",
      twitter: "https://twitter.com/313Labs",
      discord: "#",
      website: "https://313labs.io/",
      category: "Inner Discord,Role Gestion",
      from: "#FF6163",
      to: "#201B01",
    },
    {
      name: "Kalisten",
      description:
        "Use your Supportive Dude to track your workouts, progress your NFT, Train2Earn, and earn $KST that you can directly swap to $USDC.",
      icon: "https://cdn.discordapp.com/attachments/1021030450371772446/1035656455082213456/Kalisten_Logo_Gradient.png",
      twitter: "https://twitter.com/kalisten_",
      discord: "https://discord.com/invite/kalisten",
      website: "https://train.kalisten.app/",
      category: "Train-2-Earn",
      from: "#B09717",
      to: "#FB8028",
    },
    {
      name: "The Castle",
      description:
        "Holders can use their $EDD tokens to claim whitelist roles through Your Majesty by The Castle",
      icon: "https://pbs.twimg.com/profile_images/1584171267111919616/k03rOhRb_400x400.jpg",
      twitter: "https://twitter.com/nft_satori",
      discord: "https://discord.com/invite/castleking",
      website: "https://castle.thekingscastle.io/",
      category: "WL Market",
      from: "#5E5513",
      to: "#DED16A",
    },
    {
      name: "Hub3",
      description:
        "Create a personalized web3 profile, highlight your favorite NFTs, and join whitelists to empower your web3 experience.",
      icon: "https://hub3.ee/favicon.png",
      twitter: "https://twitter.com/hub3ee",
      discord: "https://discord.com/invite/d49SfuhApQ",
      website: "https://hub3.ee/app/collections/soleddarity-",
      category: "WL Gestion,Portfolio Tracker",
      from: "#581A99",
      to: "#4E1D5B",
    },
    {
      name: "Unirexcity",
      description:
        "Spend your $EDD to rename your NFTs! Naming ceremony is the first tool on Solana allowing NFTs to be named",
      icon: "https://pbs.twimg.com/profile_images/1554146782195720195/cCrUFbTU_400x400.jpg",
      twitter: "https://twitter.com/unirexcity",
      discord: "https://discord.com/invite/unirexcity",
      website: "https://naming-ceremony.unirex.city/",
      category: "NFT Renaming",
      from: "#30C132",
      to: "#E7CB1A",
    },
    {
      name: "Parrot",
      description:
        "Access the Portfolio Tracker from Parrot Tools. They are building a Solana NFT Copy Trading Platform. Investors make more profitable trades. Traders make passive income.",
      icon: "https://cdn.discordapp.com/attachments/1011202479171571812/1026491471471329300/125.png",
      twitter: "https://twitter.com/ParrotTools",
      discord: "https://discord.gg/parrotflock",
      website: "https://www.parrottrading.com/app/portfolio",
      category: "Portfolio Tracker,Copy Trading",
      from: "#003748",
      to: "#4AE486",
    },
    {
      name: "Solpix",
      description:
        "An exclusive DAO dedicated to the empowerment of the Solana community.",
      icon: "https://media.discordapp.net/attachments/1021030450371772446/1035656596405092382/FfTC06SWAAQlQB0.jpg",
      twitter: "https://twitter.com/solpixdao",
      discord: "https://discord.gg/sxA945rkCp",
      website: "https://solpix.io/",
      category: "Inner Discord,Alpha Calls,P2P,Analytics",
      from: "#CDD794",
      to: "#F7B215",
    },
    {
      name: "Rethinkable",
      description:
        "Discord based Web3 recruitment solution that supports projects, communities, and individuals",
      icon: "https://pbs.twimg.com/profile_images/1552653202189086721/gVFMyO2K_400x400.jpg",
      twitter: "https://twitter.com/rethinkablexyz",
      discord: "https://discord.com/invite/rethinkable",
      website: "https://www.rethinkable.xyz/",
      category: "Inner Discord,Job Offers",
      from: "#2D75FA",
      to: "#112C5F",
    },
    {
      name: "Satori",
      description:
        "Trading tools, Analytics Platform on Solana",
      icon: "https://cdn.discordapp.com/attachments/1011202479171571812/1027220196005519522/-9He2j8XSuR-rG5UNYvQCjV_ycjIbI1sr_SoD_PDY6A.png",
      twitter: "https://twitter.com/nft_satori",
      discord: "https://discord.gg/besatori",
      website: "https://satori-nft.io/",
      category: "Inner Discord,Alpha Calls,Analytics",
      from: "#57DCF7",
      to: "#2F527C",
    },
    {
      name: "Sol Decoder",
      description:
        "A suite of tools to find/judge hype of mints. Earn XP by chatting and completing tasks, get weekly rewards",
      icon: "https://soldecoder.app/assets/site-logos/logo-transparent.png",
      twitter: "https://twitter.com/SOL_Decoder",
      discord: "https://discord.com/invite/s4ne34TrUC",
      website: "https://soldecoder.app/",
      category: "Inner Discord,Engage-2-Earn,Analytics",
      from: "#647FE1",
      to: "#76E5CD",
    },
    {
      name: "NexiLabs",
      description:
        "Nexi Labs is an All-In-One Defi Platform that integrates Solana wallets into Discord",
      icon: "https://moon.ly/uploads/nft/1cbff083-93a8-44ac-9a69-3f3e55d1d87a.jpg",
      twitter: "https://twitter.com/NexiLabs",
      discord: "https://discord.com/invite/nexi",
      website: "https://www.nexilabs.io/",
      category: "Inner Discord,Analytics",
      from: "#161203",
      to: "#B0A98C",
    },
    {
      name: "Matrica",
      description:
        "NFT-based verification, token-gating, and voting services to Discord servers, and an NFT wallet. ",
      icon: "https://nftsolana.io/wp-content/uploads/2021/09/nX5X4u3w_400x400.jpg",
      twitter: "https://twitter.com/MatricaLabs",
      discord: "https://discord.com/invite/MatricaLabs",
      website: "https://matrica.io/community/sol-edda-rity",
      category: "Portfolio Tracker,Verification",
      from: "#83C2AA",
      to: "#494E6C",
    },
  ];

  export const discounts = [
    {
      name: "Oak Paradise",
      description:
        "Oak Paradise is building sportsbook, casino and poker room featuring Solana and SPL Tokens, E-Sports betting and custom games, such as Pawnshop, NFT Jackpot and Sports Alpha.",
      icon: "https://creator-hub-prod.s3.us-east-2.amazonaws.com/oak_paradise_pfp_1661193184623.jpeg",
      twitter: "https://twitter.com/oakparadisenft",
      discord: "https://discord.com/invite/oakdystopia",
      website: "https://registration.oak.bet/?referral=Soleddarity",
      category: "Casino,P2E,SportsBook",
      from: "#5C8656",
      to: "#314631",
    },
    {
      name: "Scalp Empire",
      description:
        "-23% on the monthly subscription. Analytic tools, sniping bot ... anything you need as a scalper.",
      icon: "https://www.scalp-empire.com/v4/se_logo-192x192.png",
      twitter: "https://twitter.com/ScalpEmpireNFT",
      discord: "https://discord.com/invite/scalpempire",
      website: "https://www.scalp-empire.com/subscribe/soleddarity",
      category: "Sniper Bot",
      from: "#152E4C",
      to: "#6E83A3",
    },
    {
      name: "Parrot",
      description:
        "-20% discount on traders subscription fees. Parrot Tools are building a Solana NFT Copy Trading Platform. Investors make more profitable trades. Traders make passive income.",
      icon: "https://cdn.discordapp.com/attachments/1011202479171571812/1026491471471329300/125.png",
      twitter: "https://twitter.com/ParrotTools",
      discord: "https://discord.gg/parrotflock",
      website: "https://www.parrottrading.com/app/portfolio",
      category: "Portfolio Tracker,Copy Trading",
      from: "#003748",
      to: "#4AE486",
    },
    {
      name: "Doge Capital",
      description:
        "Enjoy the Supportive Dude benefits by having a multitude of discounts on Doge Capital services",
      icon: "https://dl.airtable.com/.attachmentThumbnails/5e07dff05059715ef2478b80cfee0c99/41bbd847",
      twitter: "https://twitter.com/thedogecapital",
      discord: "https://discord.gg/generousrobots",
      website: "https://thedogecapital.com/",
      category: "Utility Tools",
      from: "#E5BD63",
      to: "#907539",
    },
    {
      name: "SolBookie",
      description:
        "25% bonus on ALL your deposits on the premier sports betting destination in the Solana ecosystem",
      icon: "https://cdn.discordapp.com/attachments/1021030450371772446/1035678239470919710/download.jpg",
      twitter: "https://twitter.com/solbookienft",
      discord: "https://discord.com/invite/SolBookieNFT",
      website: "https://solbookie.io/",
      category: "SportsBook",
      from: "#5B9EB8",
      to: "#642FDA",
    },
  ];

  export const games = [
    {
      name: "Soleddarity's CoinFlip",
      description:
        "Bet in SOL or $EDD in a 50/50 coin flip. 2.5% fee on each games shared with the dudes.",
      icon: "https://pbs.twimg.com/profile_images/1583022448844460034/YqGEyBmC_400x400.jpg",
      twitter: "#",
      discord: "discord.gg/soleddarity",
      website: "https://soleddarity-coinflip.vercel.app/",
      category: "Coin Flip, Betting",
      from: "#7C9CD8",
      to: "#8E68D5",
    },
    {
      name: "EDD's Multiflip",
      description:
        "Flip in $EDD or Solana with up to 10x Multipliers and 1-click lightning fast transactions",
      icon: "https://img.freepik.com/vecteurs-premium/solana-sol-crypto-monnaie-piece-orechange-argent-numerique_268461-144.jpg?w=740",
      twitter: "#",
      discord: "discord.gg/soleddarity",
      website: "https://edd.multiflip.io/",
      category: "Multiflip",
      from: "#C7AE35",
      to: "#03C2BC",
    },
    {
      name: "DegenDevil",
      description:
        "Holders get a 50% deposit bonus on this Solana based full service casino with a sportsbook, live casino games, virtual sport and more!",
      icon: "https://pbs.twimg.com/profile_images/1595460707470176256/7U3IBMuR_400x400.jpg",
      twitter: "https://twitter.com/SKULLBOTS",
      discord: "https://discord.com/invite/skullbots",
      website: "https://degendevil.com/?ref=supportive",
      category: "Casino,SportsBook,P2E",
      from: "#000000",
      to: "#D91313",
    },
    {
      name: "AibaverseNFT",
      description:
        "???",
      icon: "https://pbs.twimg.com/profile_images/1588377913077878784/xjWbnSb1_400x400.jpg",
      twitter: "https://twitter.com/aibaversenft",
      discord: "discord.gg/8uBvkjNp9Z",
      website: "#",
      category: "Social Simulation",
      from: "#B929FF",
      to: "#22072F",
    },
{
      name: "Shuffle by Immortals",
      description:
        "PVP betting games to Web3",
      icon: "https://pbs.twimg.com/profile_images/1602577769359151111/bW5dZD_h_400x400.jpg",
      twitter: "https://twitter.com/immortalsSOL",
      discord: "discord.gg/immortalsSOL",
      website: "https://www.solanashuffle.com/jackpot/1bbd7349-15cc-4ffc-95ad-3bff22108aa8",
      category: "Betting",
      from: "#14171F",
      to: "#2B3039",
    },
    {
      name: "Solcrash.io",
      description:
        "The highest adrenaline crypto game on Solana",
      icon: "https://pbs.twimg.com/profile_images/1507197976158126082/KXhKpePV_400x400.jpg",
      twitter: "https://twitter.com/solcrash",
      discord: "discord.gg/solcrash",
      website: "https://solcrash.io/?code=Dudes",
      category: "Betting",
      from: "#544F64",
      to: "#068FC7",
    },
    {
      name: "Oak Poker Paradise",
      description:
        "Oak Paradise is building sportsbook, casino and poker room featuring Solana and SPL Tokens, E-Sports betting and custom games, such as Pawnshop, NFT Jackpot and Sports Alpha.",
      icon: "https://creator-hub-prod.s3.us-east-2.amazonaws.com/oak_paradise_pfp_1661193184623.jpeg",
      twitter: "https://twitter.com/oakparadisenft",
      discord: "https://discord.com/invite/oakdystopia",
      website: "https://registration.oak.bet/?referral=Soleddarity",
      category: "Casino,Poker",
      from: "#5C8656",
      to: "#314631",
    },
  ];

  export const educations = [
    {
      name: "Max Educational Platform",
      description: "Sharing knowledge on the Solana NFT market @MaxbrsNFT",
      icon: "https://cdn.discordapp.com/attachments/1021030450371772446/1034516444408459384/Capture_decran_2022-10-25_a_19.18.31.png",
      twitter: "#",
      discord: "#",
      website:
        "https://maxbrs.notion.site/Max-Educational-Platform-0459f9ed8e3a418ea07854a5595adcf2",
      category: "Full Guide",
      from: "#9AC786",
      to: "#6BCF39",
    },
{
      name: "Solana NFT Review",
      description: "Your #1 resource for Solana NFT education",
      icon: "https://pbs.twimg.com/profile_images/1491548889182265352/bhWpS1Pn_400x400.jpg",
      twitter: "https://twitter.com/ReviewSolana",
      discord: "#",
      website:
        "https://t.co/W06ZhRt78E",
      category: "Review",
      from: "#7C9CD8",
      to: "#03C2BC",
    },
    {
      name: "Ledger Academy",
      description: "Ledger academy is here to provide you with all the content you need to safely navigate Web3. Learn crypto on your own terms.",
      icon: "https://finance-et-compagnies.com/storage/media/1244/N44_mYZ7_400x400.jpg",
      twitter: "#",
      discord: "#",
      website: "https://www.ledger.com/academy",
      category: "Full Guide",
      from: "#1C1C1C",
      to: "#DFB0B0",
    },
    {
      name: "Magic Eden's Intro to Solana NFTs",
      description:
        "Get to know the basic of NFts and Solana Blockchain on the official's Magic Eden guide",
      icon: "https://yt3.ggpht.com/HRtpijPgB6rijcMFphGjxEUb5QGFdGFpLVzE_harHbuAi-7VP0S8-2ihkRxF8okOkZo2_yINBw=s900-c-k-c0x00ffffff-no-rj",
      twitter: "https://twitter.com/MagicEden",
      discord: "https://discord.com/invite/magiceden",
      website: "https://contenthub.magiceden.io/playbook",
      category: "Full Guide",
      from: "#950BC6",
      to: "#B657A9",
    },
  ];
